gg:
  keystore:
    type: PKCS12
    path: "/clientCertificate.p12"
    password: "market99!@#"

  google:
    client-id: 311647926900-0t06lfs4l1ci1qsgpoc15s1g71121asq.apps.googleusercontent.com
    client-key: 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

  jwt:
    secret-url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/2e2391a7260646499390dc43b38a3cd0
    expire-time: 1800000            # 30 minutes
    refresh-expire-time: 604800000  # 7 days

  mail:
    username: marketgg.bot
    password: dehonihcpkjtftar
    host: 127.0.0.1
    port: 7070

  protocol: TLS

  redis:
    url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/5408ab7824e3463fa31f054b9e5f19f8
    password-url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/42c84798d4784e83be3c568a75809829
    # url: 133.186.211.156:6379:17
    # Caused by: org.yaml.snakeyaml.composer.ComposerException: found undefined alias
    # password-url: *N2vya7H@muDTwdNMR!

server:
  port: 7070

spring:
  application:
    name: marketgg-auth

  messages:
    basename: i18n/exception
    encoding: UTF-8

  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: local, dev-file-logging, dev-db
  #    group:
#      local: common, testdb, local-file-logging
#      dev: common, devdb, dev-file-logging
#      prod: common, devdb, dev-file-logging


---

spring:
  config:
    activate:
      on-profile: local-file-logging

logging:
  config: classpath:log4j2-local.xml

---

spring:
  config:
    activate:
      on-profile: dev-file-logging

logging:
  config: classpath:log4j2-dev.xml

---

spring:
  config:
    activate:
      on-profile: local

gg:
  google:
    redirect-uri: http://127.0.0.1:5050/login/oauth2/code/google

---

spring:
  config:
    activate:
      on-profile: dev

gg:
  google:
    redirect-uri: http://marketgg.shop/login/oauth2/code/google

---

spring:
  config:
    activate:
      on-profile: common

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      decorator:
        datasource:
          p6spy:
            enable-logging: true

---

spring:
  config:
    activate:
      on-profile: testdb

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:~/h2/test/testdb;MODE=MYSQL
      username: sa

---

spring:
  config:
    activate:
      on-profile: devdb

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.211.156:3306/marketgg_auth
    username: on7
    password: ?nk9Wa#^Bg)on71!*,^2=d

  jpa:
    properties:
      decorator:
        datasource:
          p6spy:
            enable-logging: false
