spring:
  application:
    name: marketgg-auth

  config:
    import: "optional:configserver:http://133.186.209.70:8888"

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:~/h2/test/testdb;MODE=MYSQL
      username: sa

  messages:
    basename: i18n/exception
    encoding: UTF-8

  main:
    allow-bean-definition-overriding: true